export const ON_SUCCESS_FETCH_AREAS = 'ON_SUCCESS_FETCH_AREAS';
export const ON_SAVE_MILESTONES_ANSWER = 'ON_SAVE_MILESTONES_ANSWER';
export const ON_SUCCESS_FETCH_AREA_BY_ID = 'ON_SUCCESS_FETCH_AREA_BY_ID';
export const ON_SUCCESS_FETCH_SKILL_BY_ID = 'ON_SUCCESS_FETCH_SKILL_BY_ID';
